### ISSUE TITLE
Ability to use external PostgreSQL database

### ISSUE THREAD

**Issue by mtnezm** [eduardogsilva/routerfleet#1]
Hi,

By any chance is it possible to specify an external PostgreSQL database endpoint, maybe via environment variables? I'm wondering since only the POSTGRES_PASSWORD variable seems enabled to be defined by the user, [but the HOST one is already there too](https://github.com/eduardogsilva/routerfleet/blob/c55ab5d88e7b463e360af7db424e28c427665e2e/entrypoint.sh#L31).

Thanks and keep up with the good work.

**Comment by eduardogsilva** [comment]
Hello @mtnezm ! 

Yes, it's possible, I just used the POSTGRES_PASSWORD variable to not ship a default password. 
I'm planning to use an image host. I just need to check some best practices first. 

I will leave this issue open, and I will add this soon.
Meanwhile, you can edit the routerfleet/production_settings.py in your running container and insert your database settings.
warning: This file will be lost if you rebuild the container.

**Comment by eduardogsilva** [comment]
@mtnezm It's done! :)
Please check the upgrade instructions, it changed a bit.
