### ISSUE TITLE
Let users import previous backups

### ISSUE THREAD

**Issue by enduring78** [eduardogsilva/routerfleet#16]
I don't know if many people have this, but I have a collection of unencrypted .backup files stored in a folder. Would it be possible to import them? I get it if the diff function does not work, but at least having the backups listed in one place would make things a lot easier.

**Comment by eduardogsilva** [comment]
Hi, it's not impossible, but I believe that it's a bit out of scope. 
Also, there will be a lot of small details needed to be implemented to make this happen. I believe that this will consume a lot of hours of coding that could be dedicated in other points.

Thanks for the suggestion.
