### ISSUE TITLE
Router address doesn't allow long address

### ISSUE THREAD

**Issue by craigmcfly** [eduardogsilva/routerfleet#2]
The hostname allows for a lot of characters, but the address field only allows for a few (by the look of it an IPv4 address). It doesn't allow for a router hostname or a IPv6 address.

**Comment by eduardogsilva** [comment]
The "address" field was supposed to work with IP address and hostnames. 
I forgot to change the model field size. It's done now. Thank you for pointing it out.

I also added the upgrade instructions to the readme file. :)

Thank you!

**Comment by craigmcfly** [comment]
I had a look at the upgrade instructions, but it's unclear how to do a pg_dump given that the postgres app is in a container. You might want to elaborate on that bit.

**Comment by eduardogsilva** [comment]
@craigmcfly I've updated the README to include the pg_dump command. ;)
