### ISSUE TITLE
Possibility of custom SSH port

### ISSUE THREAD

**Issue by fabriciomatrix** [eduardogsilva/routerfleet#21]
Hi, this project is really good! I used "cBackup" but unfortunately I haven't received an update in a long time.

I use a different SSH port than the default, but I didn't find a way to make it work in the tool

ps: You're probably Brazilian like me, but I preferred to write in my pseudo English

![image](https://github.com/eduardogsilva/routerfleet/assets/86535948/d6312781-fc8b-47c8-96c0-d62778458533)

cBackup Picture

**Comment by fabriciomatrix** [comment]
Nice! Precisando de colaboração, me ponho a disposição. Uso o mesme nome de usuário no telegram

**Comment by eduardogsilva** [comment]
@fabriciomatrix The new version now supports changing the default ssh port ;)
