### ISSUE TITLE
"Error connecting to API" when trying to link to wireguard_webadmin

### ISSUE THREAD

**Issue by Zebble** [eduardogsilva/routerfleet#29]
Does this feature work?

I've tried to integrate RouterFleet with wireguard_webadmin and I just get "Error connecting to API".  There are no additional details in the logs, even with DEBUG_MODE set to True on both RouterFleet and wireguard_webadmin.

- I've created the uuid/api key using the instructions on the integration page in RouterFleet
- I've confirmed that once this is completed, I can no longer log into wireguard_webadmin

For "Integration url" I've tried both "https://<FQDN of wireguard_webadmin" and "https://<ip address of wireguard_webadmin" to no avail.

I assume that "Token" is the same as "API Key" is the same as "uuid"/"routerfleet_key"?

**Comment by eduardogsilva** [comment]
Hello, I will be closing this issue since I believe that it's clarified now. 
Please reopen this issue if you still need assistance. 

Cheers!
