### ISSUE TITLE
Feature Request - disable check to updates.eth0.com.br

### ISSUE THREAD

**Issue by enduring78** [eduardogsilva/routerfleet#31]
Currently, Routerfleet regurarly pings updates.eth0.com.br, I assume for updates. 

Because we ant maximum security, any calls made directly to the internet are blocked. This resulted in a low of dropped packets, which is unfortunate because it is using up some % of CPU power. Therefore, it would be nice to be able to disable these checks.

**Comment by eduardogsilva** [comment]
Hello @enduring78 you can safely disable the check updates call by loging in to cron container and commenting out the line that calls the check update functions on the file "/etc/cron.d/cron_tasks" (it's the line that ends in /cron/check_updates/)

You should also consider reviewing the code for this view if you wish. There's no funny things there, just a routine to identify if you have any update available.

If you remove the check update function, I strongly suggest that you somehow monitor routerfleet for new versions. we are not in the 1.0 release yet, and we are under heavy development. I'm still releasing bug fixes, new features and improvements  on a daily basis.

Cheers!
