### ISSUE TITLE
Backup not running

### ISSUE THREAD

**Issue by craigmcfly** [eduardogsilva/routerfleet#4]
I've created a backup at 20:53 UTC, but it says "5:53 p.m" on the management page, suggesting that the code is hardcoded to a USA timezone.

The backup is yet to run, and I can't find any logs. The status is "Backup pending Retrieval"

**Comment by eduardogsilva** [comment]
Yes, the timezone is hardcoded and I will fix this pretty soon. 

Did you create an instant backup? In this case, it will be run on next cron job.

A backup with "Backup pending retrieval", means that the backup command was already sent to the router and it's waiting for the "Retrieve interval". 

The default retrieve interval is 1 Minute and you can change this editing the backup profile. (but it wont change the current retrieval time for this backup).
Try to refresh the page after a while to see if the backup is already completed.

**Comment by craigmcfly** [comment]
I created it several hours ago. I'm not seeing any auth attempts to my router.

**Comment by eduardogsilva** [comment]
Can you check if your cron container is running?
Also, can you please take a look on the main container logs? we are looking for urls with cron path.


`docker logs -f routerfleet`


`[05/Apr/2024 10:29:01] "GET /cron/perform_backup_tasks/ HTTP/1.1" 200 29
[05/Apr/2024 10:30:01] "GET /cron/generate_backup_schedule/ HTTP/1.1" 200 252
[05/Apr/2024 10:30:01] "GET /cron/check_updates/ HTTP/1.1" 200 27
[05/Apr/2024 10:30:01] "GET /cron/perform_backup_tasks/ HTTP/1.1" 200 29
[05/Apr/2024 10:30:01] "GET /cron/create_backup_tasks/ HTTP/1.1" 200 102
[05/Apr/2024 10:30:01] "GET /cron/housekeeping/ HTTP/1.1" 200 54
[05/Apr/2024 10:31:01] "GET /cron/check_updates/ HTTP/1.1" 200 27
[05/Apr/2024 10:31:01] "GET /cron/create_backup_tasks/ HTTP/1.1" 200 102
`


I will make a few changes to the project now, so it's easier to troubleshoot.
- add an env variable for timezone
- add tooltip for giving hints on why the backup is waiting.


I will let you know when it's ready for upgrade.

**Comment by eduardogsilva** [comment]
Hello @craigmcfly 
I made some important modifications do help identify whats going on in your case.

1- Added timezone configuration. Just check the deploy/upgrade instructions and pick your timezone.
2- added a cron monitoring tool. If your cron jobs are not running, they will be easily spotted on the next item
3- a bunch of debug information displayed on the backup page, giving a very good idea of what is going on with the backup.

Can you please upgrade your installation and show me a print screen of your backup details page ?

Thank you!

**Comment by craigmcfly** [comment]
Upgrade done. Thanks for fixing the timezone :) 

The crons are definitely showing in the docker logs. Here's the recent output from the GUI
<img width="441" alt="Screenshot 2024-04-06 at 12 08 02" src="https://github.com/eduardogsilva/routerfleet/assets/24719873/6af3c610-f64c-4f2a-a829-5e318e0898ba">

**Comment by eduardogsilva** [comment]
I forgot to add a "current timestamp" to this screen lol.
Supposing that your cron is running fine, and you took this screenshot at ~12:06pm.

I can see that your retry count is 1, and your next retry is scheduled to 30 minutes ahead (the next retry will only happen after the next retry timestamp)

For what I can see, routerfleet was able to connect to your router, but was not able to retrieve the backup. 

Please, edit your backup profile, and reduce the retry interval to one minute and max retry to one.
Run a new backup and wait for it to fail. I would like to see the error message. 

Do you have any non ascii characters on your router name and address? Can you share those names with us or at least describe how they are formed?

what's your router os version?

**Comment by craigmcfly** [comment]
It was an instant backup that I ran, and the pic was taken at 12:08.

The router is "nevertik" (top left of the pic) and the IP address is just a standard 192.168.X.Y address.

**Comment by craigmcfly** [comment]
<img width="619" alt="Screenshot 2024-04-06 at 13 00 31" src="https://github.com/eduardogsilva/routerfleet/assets/24719873/db8a6389-f44e-43d9-9c2f-5435b3c10272">
Oh, this is probably why. You haven't stated what permissions the user needs.

**Comment by eduardogsilva** [comment]
Well glad to hear you found the reason. 
I've also noticed that I forgot to display the last error message on the debug information. 
For now, if you change the suggested admin user, you will need to make sure that the new user have the permissions to run and retrieve the backup.

**Comment by craigmcfly** [comment]
You should probably put in your documentation that the user requires full permissions.
