### ISSUE TITLE
Page fully redraws after each link

### ISSUE THREAD

**Issue by craigmcfly** [eduardogsilva/routerfleet#8]
When I click on a link, the entire page redraws from the bottom up and there is an couple of seconds of delay as it happens.

**Comment by eduardogsilva** [comment]
Hello, I will come back to this later. it's just a css animation.

**Comment by eduardogsilva** [comment]
I tooke a quick look on the base.html and couldn't find the class responsible for the animation. If you can find it, please let me know.

**Comment by eduardogsilva** [comment]
Hello, the animation is removed! Page transition should look a lot faster now.

Cheers
